name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Project
      run: mvn clean package

    - name: Run Unit Tests
      run: mvn test

    - name: Debug List Target Directory
      run: ls -lh ./target

    # ✅ Upload JAR to EC2
    - name: Upload JAR to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: target/gym-crm-spring-core-1.0-SNAPSHOT.jar
        target: /home/ubuntu/app/
        strip_components: 1

    # ✅ Create deploy script on EC2
    - name: Create Deploy Script on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cat << 'EOF' > /home/ubuntu/deploy.sh
          #!/bin/bash
          echo "🔄 Stopping old app (if running)"
          pkill -f gym-crm-spring-core-1.0-SNAPSHOT.jar || true

          echo "🚀 Running app once"
          java -jar /home/ubuntu/app/gym-crm-spring-core-1.0-SNAPSHOT.jar > /home/ubuntu/app/app.log 2>&1 || echo "❌ App failed" >> /home/ubuntu/app/app.log

          echo "✅ App finished execution at $(date)" >> /home/ubuntu/app/app.log
          EOF
          chmod +x /home/ubuntu/deploy.sh

    # ✅ Run deploy script
    - name: Deploy and Run on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: /home/ubuntu/deploy.sh

    # ✅ Wait for log flush
    - name: Wait for log generation
      run: sleep 5

    # ✅ Print Log Directly from EC2 and verify
    - name: Print and Verify Deployment Log
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "=== EC2 Deployment Log ==="
          cat /home/ubuntu/app/app.log || echo "❌ app.log missing"
          echo "=== End Log ==="
          grep "✅ EC2 deployment successful" /home/ubuntu/app/app.log
