name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Project
      run: mvn clean package

    - name: Run Unit Tests
      run: mvn test

    - name: Upload JAR to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "target/gym-crm-spring-core-1.0-SNAPSHOT.jar"
        target: "/home/ubuntu/app/gymapp.jar"

    - name: Deploy and Run on EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "🔄 Stopping old app (if running)"
          pkill -f gymapp.jar || true

          echo "🚀 Starting new app"
          nohup java -jar /home/ubuntu/app/gymapp.jar > /home/ubuntu/app/app.log 2>&1 &

          sleep 5
          echo "✅ Deployment complete. Logs saved to /home/ubuntu/app/app.log"

    - name: Download Logs from EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "/home/ubuntu/app/app.log"
        target: "./app.log"

    - name: Upload Logs to GitHub Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ec2-deployment-log
        path: app.log
